apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-9-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-9
  template:
    metadata:
      labels:
        app: service-9
    spec:
      containers:
        - name: service-9
          image: blah/service-9
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: service-9-srv
spec:
  selector:
    app: service-9
  ports:
    - name: service-9
      protocol: TCP
      port: 3000
      targetPort: 3000