apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-1-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-1
  template:
    metadata:
      labels:
        app: service-1
    spec:
      containers:
        - name: service-1
          image: blah/service-1
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: service-1-srv
spec:
  selector:
    app: service-1
  ports:
    - name: service-1
      protocol: TCP
      port: 3000
      targetPort: 3000