apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-15-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-15
  template:
    metadata:
      labels:
        app: service-15
    spec:
      containers:
        - name: service-15
          image: blah/service-15
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: service-15-srv
spec:
  selector:
    app: service-15
  ports:
    - name: service-15
      protocol: TCP
      port: 3000
      targetPort: 3000