apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-3-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-3
  template:
    metadata:
      labels:
        app: service-3
    spec:
      containers:
        - name: service-3
          image: blah/service-3
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: service-3-srv
spec:
  selector:
    app: service-3
  ports:
    - name: service-3
      protocol: TCP
      port: 3000
      targetPort: 3000