apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-7-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-7
  template:
    metadata:
      labels:
        app: service-7
    spec:
      containers:
        - name: service-7
          image: blah/service-7
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: service-7-srv
spec:
  selector:
    app: service-7
  ports:
    - name: service-7
      protocol: TCP
      port: 3000
      targetPort: 3000