apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-10-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-10
  template:
    metadata:
      labels:
        app: service-10
    spec:
      containers:
        - name: service-10
          image: blah/service-10
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: service-10-srv
spec:
  selector:
    app: service-10
  ports:
    - name: service-10
      protocol: TCP
      port: 3000
      targetPort: 3000