apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-8-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-8
  template:
    metadata:
      labels:
        app: service-8
    spec:
      containers:
        - name: service-8
          image: blah/service-8
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: service-8-srv
spec:
  selector:
    app: service-8
  ports:
    - name: service-8
      protocol: TCP
      port: 3000
      targetPort: 3000